services:
  - type: web
    name: backend
    env: node
    plan: starter # upgrade if needed
    rootDir: apps/backend
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start:prod
    envVars:
      - key: NODE_ENV
        value: production

  - type: web # or static if using next export
    name: web
    env: node
    plan: starter
    rootDir: apps/frontend
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start # or "pnpm next start"
