export const Messages = {
  INVALID_CREDENTIALS: 'Invalid credentials',
  USER_NOT_FOUND: 'User not found',
  EMAIL_ALREADY_EXISTS: 'Email already exists',
  USERNAME_ALREADY_EXISTS: 'Username already exists',
  ACCOUNT_NOT_VERIFIED: 'Account not verified',
  SESSION_EXPIRED: 'Session has expired. Please log in again.',
  INVALID_TOKEN: 'Invalid token',
  ACCESS_DENIED: 'Access denied',
  PASSWORD_MISMATCH: 'Password does not match',
  OLD_PASSWORD_INCORRECT: 'Old password is incorrect',
  PASSWORD_RESET_FAILED: 'Password reset failed',
  ORGANIZATION_EXISTS: 'An organization with this email already exists',
  ORGANIZATION_NOT_FOUND: 'Organization not found',
  INVITATION_NOT_FOUND: 'Invitation not found',
  INVITATION_ACCEPTED: 'Invitation accepted',
  INVITATIONS_FETCHED: 'Invitations fetched successfully',
  INVITATION_ALREADY_ACCEPTED: 'Invitation has already been accepted',
  INVITATION_RESENT: 'Invitation resent successfully',
  WAITLIST_CREATED: 'Waitlist created successfully',
  WAITLIST_NOT_FOUND: 'Waitlist not found',
  WAITLIST_FETCHED: 'Waitlist fetched successfully',
  WAITLIST_UPDATED: 'Waitlist updated successfully',
  INVALID_UPDATE_FIELDS: 'No valid fields provided for update',
};
